### PR TITLE
Numerous Bug Fixes

### LINKED ISSUE #262: Missing Bottle Model Pixels

### LINKED ISSUE #405: [1.12.2] Botany Flower Spawning Issue
While attempting to do the Botany Mod, I ran into a weird occurrence.
Placing down 2 or more flowers onto the Botany soil makes it start Generating a bunch of different higher tier flowers such as Cornflowers at random, with random colors as well. There doesn't seem to be any rhyme or reason to it at all. 
Also, placing a vanilla flower on soil I believe is supposed to convert it into a Binnie's version of it, but sometimes it does not work whatsoever. (Vanilla Flowers do not react at all.)
The rate of random flower production is high as well, I was able to fill up a standard double chest with flowers within a few in game days.
This has been tested on both a Server, and Single Player, with the same result. 
(Direwolf20 1.8.0 and FTB Revelations 1.5.0 have the same problem)

### LINKED ISSUE #564: [1.12.2] Dupe glith
Any capsule is not spent if SHIFT + Left Button Mouse, watch the video
https://www.youtube.com/watch?v=zi7V9IM6RT8&feature=youtu.be

Mod: binnie-mods-1.12.2-2.5.1.184
Forge: 1.12.2 - 14.23.5.2775

### LINKED ISSUE #570: Excited bees causes lightning but no thunder
Excited bees with the lightning effect spawn lightning as normal, however no thunder.

Checked weather sounds was 100% and vanilla storms still cause thunder, just not Excited Bees

Unable to reproduce bug with any other type of bees due to this being my first time playing with bees in forestry/binnies, and I don't want to risk discovering breeding spoilers

### LINKED ISSUE #596: osanse orange sapling, pollen and leaves are missing a localized name
##### binnie-mods-1.12.2-2.5.1.188

Osange orange sapling, pollen and leaf block are missing a localized name.

This commit broke the localization: https://github.com/ForestryMC/Binnie/commit/20f77a4dbbef6f4dec4a367800c898724a099390

##### These are respectively displayed as:
- `extratrees.species.osangeorange.name Sapling`
- `extratrees.species.osangeorange.name Pollen`
- `extratrees.species.osangeorange.name Leaves`

image

### LINKED ISSUE #597: osanse orange sapling block missing texture
binnie-mods-1.12.2-2.5.1.188

Osange orange sapling block is missing a texture in-world.

### LINKED ISSUE #603: [1.12.2-2.5.1.188] Drinking a stacked bottle of Wheat Beer voids other bottles
Minecraft v1.12.2
Forge v2837
Binnie-Mods v1.12.2-2.5.1.188

When consuming a bottle of wheat Beer if in a stack it will consume only one yet void all the other stacked bottles.

### LINKED ISSUE #604: Fence Recipes Confused
It appears that in binnie-mods-1.12.2-2.5.1.188.jar (I have not looked at previous versions) that the fence recipes are somewhat confused.  The Full Fence and Low Fence recipes seem to produce each other's item.  Also the Wood Plank positions in the  Full Fence recipe give the opposite expected fence color configuration in the output item.  

Also, I assume as a side effect, JEI is labelling the Low Fence as the Full Fence and vice versa.

Another related item, for which I have put in a request to Quark, is that the Full Fence recipe conflicts with Quark's Chute recipe which, in my modded Minecraft game, completely masks the Full Fence recipe.  

So there is quite the tangle here...if someone wants to craft a Full Fence they will have to actually craft what JEI calls the Low Fence and if they want the Low Fence they will craft the Full Fence per JEI and then also discover they must reverse the expected Wood Plank positions to get the correct resulting color orientation on the output Fence.

### LINKED ISSUE #605: Damp soil loses moisture
I'm playing in the direwolf20 1.12 pack and had to resort to getting damp soil using creative because no matter what biome I tried, jungle included, none were 'damp'. Then when I put the soil down, surrounded by water, in a few different biomes including river and ocean it turns to normal moisture within a minute or so.

Edited to add, I also can't find, create or keep dry soil, it's not just damp soil.

### LINKED ISSUE #607: Blooming bee recognize only vanilla saplings.
minecraft 1.12.2
binnie 1.12.2-2.5.1.188
forge 8.0.99.99

Blooming bee recognize only vanilla saplings.
None of the forestry or extra tree saplings are recognize as the flowers.

### PR DESCRIPTION
**Pull request by nstearns96**
Fixed Botany Soil incorrectly getting biome information for moisture and acidity (Fixes: #605 )
Fixed Compartment SearchDialog render bug  (Fixes: #610 )
Blooming Bee now recognizes all saplings as flowers (Fixes: #607 )
Blooming Bee bone meal effect now applies to all saplings
Fixed fence type name error (Fixes: #604 )
Fixed OsangeOrange typo (Fixes: #596 )
Fixed addFermentation typo
Fixed OsangeOrange sapling not having in-world texture (Fixes: #597 )
Fixed Avocado typo
Drinking from a stack of bottles no longer clears them all out, returning one empty bottle (Fixes: #603 )
Fixed Shift-clicking capsules in machines not consuming the capsule (Fixes: #564 )
Lit redstone ore now recognized as a flower for redstone bees
Lightning spawned from bees now plays sounds (Fixes: #570 )
 Flower mutations now work properly (Fixes: #405 )
Eliminated use of some deprecated functions
Shearing immature flowers no longer reduces durability of shears
Eliminated numerous texture warnings
Eliminated numerous prefix warnings
Fixed Rain Shield typo
Fixed Alveary typo
Fruit Press now gives correct amount of fluid output (Fixes: #612 )
Fluid Tiles in JEI now have proper names
Fixed Binnie Core bottle textures (Fixes: #262 )

### CODE REVIEW

**Comment by nstearns96** [comment]
Drinking from a stack of bottles no longer clears them all out, returning one empty bottle (Fixes: #603 )

**Comment by nstearns96** [comment]
Fixed Shift-clicking capsules in machines not consuming the capsule (Fixes: #564 )
Lit redstone ore now recognized as a flower for redstone bees
Lightning spawned from bees now plays sounds (Fixes: #570 )

**Comment by nstearns96** [comment]
Flower mutations now work properly (Fixes: #405 )
Eliminated use of some deprecated functions
Shearing immature flowers no longer reduces durability of shears
Eliminated numerous texture warnings
Eliminated numerous prefix warnings
Fixed Rain Shield typo
Fixed Alveary typo
Fruit Press now gives correct amount of fluid output (Fixes: #612 )
Fluid Tiles in JEI now have proper names
Fixed Binnie Core bottle textures (Fixes: #262 )

**Comment by nstearns96** [comment]
This is as much as I feel comfortable fixing for now. Anything more significant will require large rewrites or adding more content to the mod. I would appreciate it if I could get a review or approval for this request soon.

File: botany/src/main/java/binnie/botany/genetics/Flower.java [hunk 1]
```diff
@@ -253,10 +253,13 @@ public IFlower getOffspring(World world, BlockPos pos) {
...
-		for (IFlowerMutation mutation2 : BotanyCore.getFlowerRoot().getMutations(true)) {
-			float chance = mutation2.getChance(world, pos, alleleFirst, alleleSecond, genome0, genome2);
-			if (chance > 0.0f && world.rand.nextFloat() * 100.0f < chance && template == null) {
-				template = BotanyCore.getFlowerRoot().templateAsChromosomes(mutation2.getTemplate());
+		for (IFlowerMutation mutation : BotanyCore.getFlowerRoot().getMutations(false)) {
+			if(mutation.getAllele0().equals(alleleFirst) && mutation.getAllele1().equals(alleleSecond)) {
+				float chance = mutation.getChance(world, pos, alleleFirst, alleleSecond, genome0, genome2);
+				if (chance > 0.0f && world.rand.nextFloat() * 100.0f < chance) {
+					template = BotanyCore.getFlowerRoot().templateAsChromosomes(mutation.getTemplate());
+					break;
```
Comment (temp1011) [inline botany/src/main/java/binnie/botany/genetics/Flower.java:261]: Might be worth setting `parentFirst` here before breaking out of the loop for clarity?

File: botany/src/main/java/binnie/botany/modules/ModuleFlowers.java [hunk 2]
```diff
@@ -112,7 +113,7 @@ public void registerItemsAndBlocks() {
 		Botany.proxy.registerItem(pollen);
 		Botany.proxy.registerItem(seed);
 
-		BinnieCore.getBinnieProxy().registerTileEntity(TileEntityFlower.class, "botany.tile.flower");
+		BinnieCore.getBinnieProxy().registerTileEntity(TileEntityFlower.class, new ResourceLocation("botany:tile.flower"));
```
Comment (temp1011) [inline botany/src/main/java/binnie/botany/modules/ModuleFlowers.java:116]: Is this backwards compatible? Will TEs disappear from worlds if they are already placed due to the name change?

File: extrabees/src/main/java/binnie/extrabees/genetics/ExtraBeesFlowers.java [hunk 3]
```diff
@@ -121,7 +114,7 @@ public void register() {
 				return Collections.emptyList(); // TODO: what is this supposed to be? It was Items.APPLE before.
 			}
 			case SAPLING: {
-				return Collections.singletonList(Blocks.SAPLING);
+				return ImmutableList.of(ModuleArboriculture.getBlocks().saplingGE, Blocks.SAPLING);
```
Comment (temp1011) [inline extrabees/src/main/java/binnie/extrabees/genetics/ExtraBeesFlowers.java]: Perhaps use the ore dictionary here?

**Review by temp1011 — COMMENTED** [review]
Some potential world breakage here but otherwise things look good

File: botany/src/main/java/binnie/botany/genetics/Flower.java (hunk 1 above)
Comment (nstearns96) [reply botany/src/main/java/binnie/botany/genetics/Flower.java:261]: Most likely, yes. I tried to maintain the structure of the original code as much as possible.

File: extrabees/src/main/java/binnie/extrabees/worldgen/BinnieHiveDescription.java [hunk 4]
```diff
@@ -1,8 +1,19 @@
 package binnie.extrabees.worldgen;
 
+import java.util.ArrayList;
+import java.util.List;
```
Comment (temp1011) [inline extrabees/src/main/java/binnie/extrabees/worldgen/BinnieHiveDescription.java]: These seem unnecessary?

File: botany/src/main/java/binnie/botany/modules/ModuleFlowers.java (hunk 2 above)
Comment (nstearns96) [reply botany/src/main/java/binnie/botany/modules/ModuleFlowers.java:116]: Looks like it's not backwards compatible, unfortunately

**Comment by temp1011** [comment]
You should probably move the 'fixes' lines from other comments to the first one so the issues are closed when this gets merged

File: botany/src/main/java/binnie/botany/modules/ModuleFlowers.java (hunk 2 above)
Comment (temp1011) [reply botany/src/main/java/binnie/botany/modules/ModuleFlowers.java:116]: Forestry had the same issue a while ago and we solved it with a datafixer: https://github.com/ForestryMC/ForestryMC/commit/9b4a4c2b1d0b495f180a4dfea2bcfe492546b4d0. Just have to be careful to test all the TEs are preserved

File: botany/src/main/java/binnie/botany/genetics/Flower.java (hunk 1 above)
Comment (temp1011) [reply botany/src/main/java/binnie/botany/genetics/Flower.java:261]: fair enough

File: botany/src/main/java/binnie/botany/modules/ModuleFlowers.java (hunk 2 above)
Comment (nstearns96) [reply botany/src/main/java/binnie/botany/modules/ModuleFlowers.java:116]: Great suggestion! Thanks for pointing that out to me.

File: extratrees/src/main/java/binnie/extratrees/machines/fruitpress/FruitPressLogic.java [hunk 5]
```diff
@@ -44,6 +44,9 @@ public ErrorState canProgress() {
 
 	@Override
 	protected void onFinishTask() {
+		final FluidStack tankFinish = FruitPressRecipeManager.getOutput(this.getUtil().getStack(FruitPressMachine.SLOT_CURRENT));
+		tankFinish.amount /= 25;
+		this.getUtil().fillTank((FruitPressMachine.TANK_OUTPUT), tankFinish);
```
Comment (temp1011) [inline extratrees/src/main/java/binnie/extratrees/machines/fruitpress/FruitPressLogic.java]: After looking at the code a bit more I don't think this is the correct fix. The method `onUpdate` should output the correct amount over all the cycles but it looks like there are rounding/arithmetic errors. So I think the fix is in that method not this one.

Or maybe I'm missing something about how the fruit press works

Comment (nstearns96) [reply extratrees/src/main/java/binnie/extratrees/machines/fruitpress/FruitPressLogic.java]: You know, I was unsure of that fix. It was a bit hacky to be sure. I'll take another look at that and make it better.

File: extrabees/src/main/java/binnie/extrabees/worldgen/BinnieHiveDescription.java (hunk 4 above)
Comment (nstearns96) [reply extrabees/src/main/java/binnie/extrabees/worldgen/BinnieHiveDescription.java]: Those were left over from trying to fix another bug, I'll get rid of them.

File: botany/src/main/java/binnie/botany/modules/ModuleFlowers.java (hunk 2 above)
Comment (nstearns96) [reply botany/src/main/java/binnie/botany/modules/ModuleFlowers.java:116]: The entities are backwards compatible now.

File: extrabees/src/main/java/binnie/extrabees/genetics/ExtraBeesFlowers.java (hunk 3 above)
Comment (nstearns96) [reply extrabees/src/main/java/binnie/extrabees/genetics/ExtraBeesFlowers.java]: Good idea, works just fine!

File: extratrees/src/main/java/binnie/extratrees/machines/fruitpress/FruitPressLogic.java (hunk 5 above)
Comment (nstearns96) [reply extratrees/src/main/java/binnie/extratrees/machines/fruitpress/FruitPressLogic.java]: That should be much better.

**Comment by mezz** [comment]
Thanks for contributing! 
Please submit fixes in smaller batches next time. Small PRs are easier to review, and if some issue is blocking one PR it will not prevent all your other fixes from going through.

**Comment by nstearns96** [comment]
I'll be sure to. I was originally making these fixes for a private pack but decided to contribute to the mod directly instead. The initial commit was all of my fixes beforehand and it kinda snowballed from there.

File: botany/src/main/java/binnie/botany/genetics/Flower.java (hunk 1 above)
Comment (mezz) [reply botany/src/main/java/binnie/botany/genetics/Flower.java:261]: the best way to make this code clear would be to separate this for-loop logic into a new function that returns a template or `null`

File: extratrees/src/main/resources/assets/extratrees/lang/en_US.lang [hunk 6]
```diff
@@ -725,6 +725,112 @@ extratrees.fluid.miscfluid.sugarsyrup=Simple Syrup
 extratrees.fluid.miscfluid.agavenectar=Agave Nectar
 extratrees.fluid.miscfluid.grenadinesyrup=Grenadine Syrup
 
+## Fluid Tiles
```
Comment (mezz) [inline extratrees/src/main/resources/assets/extratrees/lang/en_US.lang:728]: I would like to avoid duplicating these localization keys, can you think of a better way?

**Review by mezz — CHANGES_REQUESTED** [review]

File: extratrees/src/main/resources/assets/extratrees/lang/en_US.lang (hunk 6 above)
Comment (nstearns96) [reply extratrees/src/main/resources/assets/extratrees/lang/en_US.lang:728]: That's how forestry does it. I don't think there's a way around it, it's due to how JEI shows fluid tiles.

Comment (mezz) [reply extratrees/src/main/resources/assets/extratrees/lang/en_US.lang:728]: Hmm ok. We can fix this up some other time maybe, it's not a very big problem.

**Review by mezz — APPROVED** [review]

**Comment by sealchan1** [comment]
This is truly epic...I hope someone can now YouTube an up-to-date Botany mod spotlight and show all the basic flower breeding working as expected.
